// Code generated by Microsoft (R) AutoRest Code Generator 0.9.6.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Collections.Generic;
using System.Linq;
using ConsoleApplication.Models;
using Newtonsoft.Json.Linq;

namespace ConsoleApplication.Models
{
    public static partial class AvailablePhoneNumbersCollection
    {
        /// <summary>
        /// Deserialize the object
        /// </summary>
        public static IList<AvailablePhoneNumbers> DeserializeJson(JToken inputObject)
        {
            IList<AvailablePhoneNumbers> deserializedObject = new List<AvailablePhoneNumbers>();
            foreach (JToken iListValue in ((JArray)inputObject))
            {
                AvailablePhoneNumbers availablePhoneNumbers = new AvailablePhoneNumbers();
                availablePhoneNumbers.DeserializeJson(iListValue);
                deserializedObject.Add(availablePhoneNumbers);
            }
            return deserializedObject;
        }
    }
}
