// Code generated by Microsoft (R) AutoRest Code Generator 0.9.6.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Linq;
using Newtonsoft.Json.Linq;

namespace ConsoleApplication.Models
{
    public partial class IncomingPhoneNumber
    {
        private DateTimeOffset? _dateCreated;
        
        /// <summary>
        /// Optional. Date Created
        /// </summary>
        public DateTimeOffset? DateCreated
        {
            get { return this._dateCreated; }
            set { this._dateCreated = value; }
        }
        
        private string _friendlyName;
        
        /// <summary>
        /// Optional. Friendly Name
        /// </summary>
        public string FriendlyName
        {
            get { return this._friendlyName; }
            set { this._friendlyName = value; }
        }
        
        private bool? _mms;
        
        /// <summary>
        /// Optional. Mms Enabled?
        /// </summary>
        public bool? Mms
        {
            get { return this._mms; }
            set { this._mms = value; }
        }
        
        private string _phoneNumber;
        
        /// <summary>
        /// Optional. Phone Number
        /// </summary>
        public string PhoneNumber
        {
            get { return this._phoneNumber; }
            set { this._phoneNumber = value; }
        }
        
        private string _sid;
        
        /// <summary>
        /// Optional. Id
        /// </summary>
        public string Sid
        {
            get { return this._sid; }
            set { this._sid = value; }
        }
        
        private bool? _sms;
        
        /// <summary>
        /// Optional. Sms Enabled?
        /// </summary>
        public bool? Sms
        {
            get { return this._sms; }
            set { this._sms = value; }
        }
        
        private bool? _voice;
        
        /// <summary>
        /// Optional. Voice Enabled?
        /// </summary>
        public bool? Voice
        {
            get { return this._voice; }
            set { this._voice = value; }
        }
        
        /// <summary>
        /// Initializes a new instance of the IncomingPhoneNumber class.
        /// </summary>
        public IncomingPhoneNumber()
        {
        }
        
        /// <summary>
        /// Deserialize the object
        /// </summary>
        public virtual void DeserializeJson(JToken inputObject)
        {
            if (inputObject != null && inputObject.Type != JTokenType.Null)
            {
                JToken dateCreatedValue = inputObject["date_created"];
                if (dateCreatedValue != null && dateCreatedValue.Type != JTokenType.Null)
                {
                    this.DateCreated = ((DateTimeOffset)dateCreatedValue);
                }
                JToken friendlyNameValue = inputObject["friendly_name"];
                if (friendlyNameValue != null && friendlyNameValue.Type != JTokenType.Null)
                {
                    this.FriendlyName = ((string)friendlyNameValue);
                }
                JToken mmsValue = inputObject["mms"];
                if (mmsValue != null && mmsValue.Type != JTokenType.Null)
                {
                    this.Mms = ((bool)mmsValue);
                }
                JToken phoneNumberValue = inputObject["phone_number"];
                if (phoneNumberValue != null && phoneNumberValue.Type != JTokenType.Null)
                {
                    this.PhoneNumber = ((string)phoneNumberValue);
                }
                JToken sidValue = inputObject["sid"];
                if (sidValue != null && sidValue.Type != JTokenType.Null)
                {
                    this.Sid = ((string)sidValue);
                }
                JToken smsValue = inputObject["sms"];
                if (smsValue != null && smsValue.Type != JTokenType.Null)
                {
                    this.Sms = ((bool)smsValue);
                }
                JToken voiceValue = inputObject["voice"];
                if (voiceValue != null && voiceValue.Type != JTokenType.Null)
                {
                    this.Voice = ((bool)voiceValue);
                }
            }
        }
    }
}
