// Code generated by Microsoft (R) AutoRest Code Generator 0.9.6.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Collections.Generic;
using System.Linq;
using ConsoleApplication.Models;
using Newtonsoft.Json.Linq;

namespace ConsoleApplication.Models
{
    public static partial class IncomingPhoneNumberCollection
    {
        /// <summary>
        /// Deserialize the object
        /// </summary>
        public static IList<IncomingPhoneNumber> DeserializeJson(JToken inputObject)
        {
            IList<IncomingPhoneNumber> deserializedObject = new List<IncomingPhoneNumber>();
            foreach (JToken iListValue in ((JArray)inputObject))
            {
                IncomingPhoneNumber incomingPhoneNumber = new IncomingPhoneNumber();
                incomingPhoneNumber.DeserializeJson(iListValue);
                deserializedObject.Add(incomingPhoneNumber);
            }
            return deserializedObject;
        }
    }
}
