// Code generated by Microsoft (R) AutoRest Code Generator 0.9.6.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Collections.Generic;
using System.Linq;
using ConsoleApplication.Models;
using Newtonsoft.Json.Linq;

namespace ConsoleApplication.Models
{
    public static partial class MessageResponseCollection
    {
        /// <summary>
        /// Deserialize the object
        /// </summary>
        public static IList<MessageResponse> DeserializeJson(JToken inputObject)
        {
            IList<MessageResponse> deserializedObject = new List<MessageResponse>();
            foreach (JToken iListValue in ((JArray)inputObject))
            {
                MessageResponse messageResponse = new MessageResponse();
                messageResponse.DeserializeJson(iListValue);
                deserializedObject.Add(messageResponse);
            }
            return deserializedObject;
        }
    }
}
