// Code generated by Microsoft (R) AutoRest Code Generator 0.9.6.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Linq;
using Newtonsoft.Json.Linq;

namespace ConsoleApplication.Models
{
    public partial class SendMessageRequest
    {
        private string _body;
        
        /// <summary>
        /// Required. Content of the message
        /// </summary>
        public string Body
        {
            get { return this._body; }
            set { this._body = value; }
        }
        
        private string _fromVariable;
        
        /// <summary>
        /// Required. From Phone Number
        /// </summary>
        public string From
        {
            get { return this._fromVariable; }
            set { this._fromVariable = value; }
        }
        
        private string _mediaUrls;
        
        /// <summary>
        /// Optional. Media Content
        /// </summary>
        public string MediaUrls
        {
            get { return this._mediaUrls; }
            set { this._mediaUrls = value; }
        }
        
        private string _to;
        
        /// <summary>
        /// Required. To Phone Number
        /// </summary>
        public string To
        {
            get { return this._to; }
            set { this._to = value; }
        }
        
        /// <summary>
        /// Initializes a new instance of the SendMessageRequest class.
        /// </summary>
        public SendMessageRequest()
        {
        }
        
        /// <summary>
        /// Initializes a new instance of the SendMessageRequest class with
        /// required arguments.
        /// </summary>
        public SendMessageRequest(string fromParameter, string to, string body)
            : this()
        {
            if (fromParameter == null)
            {
                throw new ArgumentNullException("fromParameter");
            }
            if (to == null)
            {
                throw new ArgumentNullException("to");
            }
            if (body == null)
            {
                throw new ArgumentNullException("body");
            }
            this.From = fromParameter;
            this.To = to;
            this.Body = body;
        }
        
        /// <summary>
        /// Serialize the object
        /// </summary>
        /// <returns>
        /// Returns the json model for the type SendMessageRequest
        /// </returns>
        public virtual JToken SerializeJson(JToken outputObject)
        {
            if (outputObject == null)
            {
                outputObject = new JObject();
            }
            if (this.Body == null)
            {
                throw new ArgumentNullException("Body");
            }
            if (this.From == null)
            {
                throw new ArgumentNullException("From");
            }
            if (this.To == null)
            {
                throw new ArgumentNullException("To");
            }
            if (this.Body != null)
            {
                outputObject["Body"] = this.Body;
            }
            if (this.From != null)
            {
                outputObject["From"] = this.From;
            }
            if (this.MediaUrls != null)
            {
                outputObject["MediaUrls"] = this.MediaUrls;
            }
            if (this.To != null)
            {
                outputObject["To"] = this.To;
            }
            return outputObject;
        }
    }
}
