// Code generated by Microsoft (R) AutoRest Code Generator 0.9.6.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Linq;
using Newtonsoft.Json.Linq;

namespace ConsoleApplication.Models
{
    public partial class UsageRecords
    {
        private string _category;
        
        /// <summary>
        /// Optional. Category
        /// </summary>
        public string Category
        {
            get { return this._category; }
            set { this._category = value; }
        }
        
        private string _count;
        
        /// <summary>
        /// Optional. Count
        /// </summary>
        public string Count
        {
            get { return this._count; }
            set { this._count = value; }
        }
        
        private string _countUnit;
        
        /// <summary>
        /// Optional. Count Unit
        /// </summary>
        public string CountUnit
        {
            get { return this._countUnit; }
            set { this._countUnit = value; }
        }
        
        private string _description;
        
        /// <summary>
        /// Optional. Description
        /// </summary>
        public string Description
        {
            get { return this._description; }
            set { this._description = value; }
        }
        
        private DateTimeOffset? _endDate;
        
        /// <summary>
        /// Optional. End Date
        /// </summary>
        public DateTimeOffset? EndDate
        {
            get { return this._endDate; }
            set { this._endDate = value; }
        }
        
        private double? _price;
        
        /// <summary>
        /// Optional. Price
        /// </summary>
        public double? Price
        {
            get { return this._price; }
            set { this._price = value; }
        }
        
        private string _priceUnit;
        
        /// <summary>
        /// Optional. Price Unit
        /// </summary>
        public string PriceUnit
        {
            get { return this._priceUnit; }
            set { this._priceUnit = value; }
        }
        
        private DateTimeOffset? _startDate;
        
        /// <summary>
        /// Optional. Start Date
        /// </summary>
        public DateTimeOffset? StartDate
        {
            get { return this._startDate; }
            set { this._startDate = value; }
        }
        
        private string _usage;
        
        /// <summary>
        /// Optional. Usage
        /// </summary>
        public string Usage
        {
            get { return this._usage; }
            set { this._usage = value; }
        }
        
        private string _usageUnit;
        
        /// <summary>
        /// Optional. Usage Unit
        /// </summary>
        public string UsageUnit
        {
            get { return this._usageUnit; }
            set { this._usageUnit = value; }
        }
        
        /// <summary>
        /// Initializes a new instance of the UsageRecords class.
        /// </summary>
        public UsageRecords()
        {
        }
        
        /// <summary>
        /// Deserialize the object
        /// </summary>
        public virtual void DeserializeJson(JToken inputObject)
        {
            if (inputObject != null && inputObject.Type != JTokenType.Null)
            {
                JToken categoryValue = inputObject["category"];
                if (categoryValue != null && categoryValue.Type != JTokenType.Null)
                {
                    this.Category = ((string)categoryValue);
                }
                JToken countValue = inputObject["count"];
                if (countValue != null && countValue.Type != JTokenType.Null)
                {
                    this.Count = ((string)countValue);
                }
                JToken countUnitValue = inputObject["count_unit"];
                if (countUnitValue != null && countUnitValue.Type != JTokenType.Null)
                {
                    this.CountUnit = ((string)countUnitValue);
                }
                JToken descriptionValue = inputObject["description"];
                if (descriptionValue != null && descriptionValue.Type != JTokenType.Null)
                {
                    this.Description = ((string)descriptionValue);
                }
                JToken endDateValue = inputObject["end_date"];
                if (endDateValue != null && endDateValue.Type != JTokenType.Null)
                {
                    this.EndDate = ((DateTimeOffset)endDateValue);
                }
                JToken priceValue = inputObject["price"];
                if (priceValue != null && priceValue.Type != JTokenType.Null)
                {
                    this.Price = ((double)priceValue);
                }
                JToken priceUnitValue = inputObject["price_unit"];
                if (priceUnitValue != null && priceUnitValue.Type != JTokenType.Null)
                {
                    this.PriceUnit = ((string)priceUnitValue);
                }
                JToken startDateValue = inputObject["start_date"];
                if (startDateValue != null && startDateValue.Type != JTokenType.Null)
                {
                    this.StartDate = ((DateTimeOffset)startDateValue);
                }
                JToken usageValue = inputObject["usage"];
                if (usageValue != null && usageValue.Type != JTokenType.Null)
                {
                    this.Usage = ((string)usageValue);
                }
                JToken usageUnitValue = inputObject["usage_unit"];
                if (usageUnitValue != null && usageUnitValue.Type != JTokenType.Null)
                {
                    this.UsageUnit = ((string)usageUnitValue);
                }
            }
        }
    }
}
