// Code generated by Microsoft (R) AutoRest Code Generator 0.9.6.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Collections.Generic;
using System.Linq;
using ConsoleApplication.Models;
using Newtonsoft.Json.Linq;

namespace ConsoleApplication.Models
{
    public static partial class UsageRecordsCollection
    {
        /// <summary>
        /// Deserialize the object
        /// </summary>
        public static IList<UsageRecords> DeserializeJson(JToken inputObject)
        {
            IList<UsageRecords> deserializedObject = new List<UsageRecords>();
            foreach (JToken iListValue in ((JArray)inputObject))
            {
                UsageRecords usageRecords = new UsageRecords();
                usageRecords.DeserializeJson(iListValue);
                deserializedObject.Add(usageRecords);
            }
            return deserializedObject;
        }
    }
}
