FROM microsoft/dotnet:2.0-sdk AS build-env
WORKDIR /app

COPY *.csproj ./
RUN dotnet restore

COPY . ./
RUN dotnet publish -c Release -o out

FROM microsoft/dotnet:2.0-runtime
WORKDIR /app
COPY --from=build-env /app/out ./
RUN /bin/bash -c 'ls -la; chmod 777 -R /app/sinusmodel.json; ls -la'
ENTRYPOINT ["dotnet", "fncrecognizer.dll"]