## Service definition ##
application:
  schemaVersion: 1.0.0-preview1
  name: MeshAppl
  properties:
    services:
      - name: Svc2
        properties:
          description: Svc2 description.
          osType: Windows
          codePackages:
            - name: Svc2
              image: svc2:dev
              endpoints:
                - name: Svc2Listener
                  port: 20001
              environmentVariables:
                - name: ASPNETCORE_URLS
                  value: http://+:20001
#                - name: ApplicationInsights:InstrumentationKey
#                  value: "<Place AppInsights key here, or reference it via a secret>"
              resources:
                requests:
                  cpu: 0.5
                  memoryInGB: 1
          replicaCount: 1
          networkRefs:
            - name: MeshApplNetwork