FROM microsoft/dotnet AS build-sdk-env
WORKDIR /app 
COPY . ./
RUN dotnet restore
RUN dotnet publish -c Release -o out
FROM microsoft/dotnet:2.0-runtime 
WORKDIR /app
COPY --from=build-sdk-env /app/out ./
ENTRYPOINT ["dotnet", "./myjob.dll"]
