// Code generated by Microsoft (R) AutoRest Code Generator 0.9.6.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using ConsoleApplication;
using Microsoft.Rest;

namespace ConsoleApplication
{
    public static partial class DeviceExtensions
    {
        /// <param name='operations'>
        /// Reference to the ConsoleApplication.IDevice.
        /// </param>
        /// <param name='channel'>
        /// Optional.
        /// </param>
        /// <param name='rootNamespace'>
        /// Optional.
        /// </param>
        public static string TelemetryPollTrigger(this IDevice operations, string channel = null, string rootNamespace = null)
        {
            return Task.Factory.StartNew((object s) => 
            {
                return ((IDevice)s).TelemetryPollTriggerAsync(channel, rootNamespace);
            }
            , operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
        }
        
        /// <param name='operations'>
        /// Reference to the ConsoleApplication.IDevice.
        /// </param>
        /// <param name='channel'>
        /// Optional.
        /// </param>
        /// <param name='rootNamespace'>
        /// Optional.
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        public static async Task<string> TelemetryPollTriggerAsync(this IDevice operations, string channel = null, string rootNamespace = null, CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Microsoft.Rest.HttpOperationResponse<string> result = await operations.TelemetryPollTriggerWithOperationResponseAsync(channel, rootNamespace, cancellationToken).ConfigureAwait(false);
            return result.Body;
        }
    }
}
