// Code generated by Microsoft (R) AutoRest Code Generator 0.9.6.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Rest;

namespace ConsoleApplication
{
    public partial interface IDevice
    {
        /// <param name='channel'>
        /// Optional.
        /// </param>
        /// <param name='rootNamespace'>
        /// Optional.
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        Task<HttpOperationResponse<string>> TelemetryPollTriggerWithOperationResponseAsync(string channel = null, string rootNamespace = null, CancellationToken cancellationToken = default(System.Threading.CancellationToken));
    }
}
